services:
  timescaledb:
    image: timescale/timescaledb:2.25.0-pg17
    container_name: timescaledb
    environment:
      POSTGRES_USER: infoclimat
      POSTGRES_PASSWORD: infoclimat2026
      POSTGRES_DB: meteodb
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
      - ./timescaledb-env/meteodb_dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    networks:
      - bd_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U infoclimat -d meteodb"]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 40s
    restart: unless-stopped

  nginx:
    image: nginx:1.29.5-alpine3.23-perl
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app_net

  backend:
    build:
      context: ./backend
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      timescaledb:
        condition: service_healthy
    networks:
      - app_net
      - bd_net
    # Commande pour automatiser les migrations et lancer le serveur
    # Note : On peut ajouter "uv run python manage.py populate_weather_data &&" avant le runserver
    # pour peupler la base automatiquement, mais cela ralentira chaque démarrage.
    command: >
      sh -c "uv run python manage.py migrate &&
            uv run python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./.env
    networks:
      - app_net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - app_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
    networks:
      - app_net
      - bd_net
    restart: unless-stopped

volumes:
  timescaledb-data:
    driver: local
  prometheus-data:
    driver: local

networks:
  app_net:
  bd_net: